AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  WebsiteRoute53HostedZoneName:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone e.g. jamesmoriarty.xyz
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

  WebsiteRoute53DomainName:
    Type: String
    Description: The full domain name e.g. www.jamesmoriarty.xyz
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.

  WebsiteCloudfrontDistributionAcmCertificateArn:
    Type: String
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    AllowedPattern: 'arn:aws:acm:.*'

Mappings:
  RegionMap:
    us-east-1:
      S3HostedZoneId: Z3AQBSTGFYJSTF
    us-west-1:
      S3HostedZoneId: Z2F56UZL2M1ACD
    us-west-2:
      S3HostedZoneId: Z3BJ6K6RIION7M
    eu-west-1:
      S3HostedZoneId: Z1BKCTXD74EZPE
    ap-southeast-1:
      S3HostedZoneId: Z3O0J2DXBE1FTB
    ap-southeast-2:
      S3HostedZoneId: Z1WCIGYICN2BYD
    ap-northeast-1:
      S3HostedZoneId: Z2M4EHUR26P7ZW
    sa-east-1:
      S3HostedZoneId: Z31GFT0UA1I2HV

Resources:
  WebsiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteRoute53DomainName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    # DeletionPolicy: Retain

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref WebsiteS3Bucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref WebsiteS3Bucket, /*]]

  WebsiteCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - WebsiteS3Bucket
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Select [2, !Split ['/', !GetAtt WebsiteS3Bucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: 80
            HTTPSPort: 443
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Aliases:
        - !Ref WebsiteRoute53DomainName
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCloudfrontDistributionAcmCertificateArn
          SslSupportMethod: sni-only

  WebsiteRoute53AliasRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref WebsiteRoute53HostedZoneName, .]]
      RecordSets:
      - Name: !Ref WebsiteRoute53DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Cloudfront HostedZoneId https://docs.aws.amazon.com/general/latest/gr/rande.html
          DNSName: !GetAtt [WebsiteCloudfrontDistribution, DomainName]

Outputs:
  WebsiteS3BucketName:
    Value: !Ref WebsiteS3Bucket

  WebsiteCloudfrontDistributionDomainName:
    Value: !GetAtt [WebsiteCloudfrontDistribution, DomainName]

  WebsiteDomainName:
    Value: !Ref WebsiteRoute53DomainName